declare type UIViewController = any;
declare type UIApplication = any;
declare var UIApplicationDelegate: any;
declare type NSNotification = any;
declare type UIColor = any;
declare type UIButton = any;
declare type UINavigationController = any;
declare type UIGestureRecognizer = any;
declare type UILabel = any;
declare type UISwitch = any;
declare type UITextField = any;
declare type UITextView = any;
