/// <reference path="../../deps/NativeScript/bin/dist/modules/declarations.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/es-collections.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/es6-promise.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/file-system/file-system.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/data/observable/observable.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/data/observable-array/observable-array.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/core/view.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/application/application.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/color/color.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/core/dependency-observable.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/core/proxy.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/core/bindable.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/animation/animation.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/content-view/content-view.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/styling/styling.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/styling/style-property.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/styling/css-selector.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/css/reworkcss.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/frame/frame.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/page/page.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/action-bar/action-bar.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/layouts/layout-base.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/layouts/layout.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/layouts/stack-layout/stack-layout.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/layouts/dock-layout/dock-layout.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/builder/component-builder.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/builder/special-properties.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/gestures/gestures.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/text-base/text-base.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/text/formatted-string.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/text/span.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/editable-text-base/editable-text-base.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/text-view/text-view.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/text-field/text-field.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/button/button.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/label/label.d.ts" />
/// <reference path="../../deps/NativeScript/bin/dist/modules/ui/switch/switch.d.ts" />

/// DISABLED reference path="../../deps/NativeScript/bin/dist/modules/android17.d.ts" />
/// DISABLED reference path="../../deps/NativeScript/bin/dist/modules/ios.d.ts" />

/// <reference path="android17-dummy.d.ts" />
/// <reference path="ios-dummy.d.ts" />
